@startuml Database

class User <extends IPersitant> {
  - id
  - name
  - email
  - password
  - applications: Array<IApplication>
}

class Applications {
  - darkCafy : DarkCafy
}

class Face <extends IApplication> {


}

class DarkCafy <extends IApplication> {
  - neededApplications = ["face"]
  - favouriteCoffee

}

interface IApplication <extends IPersitant> {
  - neededApplications: Array<IApplication['name']>
  - name: string | unique
}

interface IPersistant {
  - maxDate: timestamp or -1
}

@enduml